version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gosec
    - revive
    - bodyclose
    - sqlclosecheck
    - rowserrcheck
    - errorlint
    - gocritic
    - misspell
    - unconvert
    - noctx
  settings:
    misspell:
      locale: US
      ignore-rules:
        - kategori
        - otentikasi
        - implementasi
        - paralel
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: increment-decrement
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
        - name: redefines-builtin-id
    gosec:
      excludes:
        - G104 # sudah dicakup errcheck
    gocritic:
      enabled-tags: [diagnostic, performance]
      disabled-checks:
        - hugeParam
  exclusions:
    generated: lax
    presets:
      - std-error-handling
    paths:
      - docs/swagger
    rules:
      - path: _test\.go
        linters: [gosec, noctx, bodyclose]

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - go-auth-clean
