package http

import (
	"context"
	"net/http"
	"time"

	"github.com/google/uuid"

	"go-auth-clean/internal/finance/app"
	"go-auth-clean/internal/finance/domain"
	"go-auth-clean/internal/platform/httpx"
	"go-auth-clean/internal/shared/pagination"
)

// listRecurringRules godoc
//
//	@Summary		List recurring rules
//	@Description	Newest first (created_at, id DESC), cursor paginated.
//	@Tags			recurring-rules
//	@Produce		json
//	@Security		BearerAuth
//	@Param			limit	query		int		false	"Page size (1-100, default 20)"
//	@Param			cursor	query		string	false	"Opaque cursor from meta.next_cursor"
//	@Success		200		{object}	RecurringRuleListEnvelope
//	@Failure		400		{object}	httpx.ErrorResponse	"INVALID_PARAMETER / INVALID_CURSOR"
//	@Failure		401		{object}	httpx.ErrorResponse	"UNAUTHENTICATED"
//	@Router			/recurring-rules [get]
func (h *Handler) listRecurringRules(w http.ResponseWriter, r *http.Request) {
	uid, ok := userID(w, r)
	if !ok {
		return
	}
	q := r.URL.Query()
	limit, err := pagination.ParseLimit(q.Get("limit"))
	if err != nil {
		httpx.WriteError(w, r, invalidParam("limit", err.Error()))
		return
	}
	filter := pagination.FilterHash("recurring-rules")
	cur, err := pagination.Decode(q.Get("cursor"), filter)
	if err != nil {
		httpx.WriteError(w, r, mapError(err))
		return
	}
	var after *domain.PageKey
	if cur != nil {
		after = &domain.PageKey{Date: cur.Time, ID: cur.ID}
	}
	rules, err := h.svc.ListRecurringRules(r.Context(), uid, limit, after)
	if err != nil {
		httpx.WriteError(w, r, mapError(err))
		return
	}
	page, meta := pagination.Page(rules, limit, filter, func(x *domain.RecurringRule) (time.Time, uuid.UUID) {
		return x.CreatedAt(), x.ID()
	})
	out := make([]RecurringRuleResponse, 0, len(page))
	for _, x := range page {
		out = append(out, toRecurringRuleResponse(x))
	}
	httpx.List(w, out, meta)
}

// createRecurringRule godoc
//
//	@Summary		Create recurring rule
//	@Description	Template transaction generated by a background worker on each occurrence (idempotent per rule + date). Monthly/yearly rules anchor on the start_date day, clamped to month end. Use end_date or count (not both). Requires Idempotency-Key.
//	@Tags			recurring-rules
//	@Accept			json
//	@Produce		json
//	@Security		BearerAuth
//	@Param			Idempotency-Key	header		string						true	"Unique key per logical request (8-128 chars)"
//	@Param			body			body		CreateRecurringRuleRequest	true	"Rule"
//	@Success		201				{object}	RecurringRuleEnvelope
//	@Failure		400				{object}	httpx.ErrorResponse	"INVALID_JSON / IDEMPOTENCY_KEY_REQUIRED"
//	@Failure		401				{object}	httpx.ErrorResponse	"UNAUTHENTICATED"
//	@Failure		404				{object}	httpx.ErrorResponse	"ACCOUNT_NOT_FOUND / CATEGORY_NOT_FOUND"
//	@Failure		409				{object}	httpx.ErrorResponse	"IDEMPOTENCY_IN_PROGRESS"
//	@Failure		422				{object}	httpx.ErrorResponse	"VALIDATION_FAILED / INVALID_FREQUENCY / CATEGORY_TYPE_MISMATCH / ACCOUNT_ARCHIVED"
//	@Router			/recurring-rules [post]
func (h *Handler) createRecurringRule(w http.ResponseWriter, r *http.Request) {
	uid, ok := userID(w, r)
	if !ok {
		return
	}
	req, err := decodeAndValidate[CreateRecurringRuleRequest](h, w, r)
	if err != nil {
		httpx.WriteError(w, r, mapError(err))
		return
	}
	in, err := createRecurringInput(uid, req)
	if err != nil {
		httpx.WriteError(w, r, err)
		return
	}
	h.idempotent(w, r, uid, "/api/v1/recurring-rules", req, func(ctx context.Context) (int, any, error) {
		x, err := h.svc.CreateRecurringRule(ctx, in)
		if err != nil {
			return 0, nil, err
		}
		return http.StatusCreated, toRecurringRuleResponse(x), nil
	})
}

func createRecurringInput(uid uuid.UUID, req CreateRecurringRuleRequest) (app.CreateRecurringInput, error) {
	in := app.CreateRecurringInput{UserID: uid, Type: req.Type, Amount: req.Amount, Note: req.Note,
		Frequency: req.Frequency, Interval: req.Interval, Count: req.Count}
	var err error
	if in.AccountID, err = uuid.Parse(req.AccountID); err != nil {
		return in, invalidParam("account_id", "harus UUID")
	}
	if in.CategoryID, err = uuid.Parse(req.CategoryID); err != nil {
		return in, invalidParam("category_id", "harus UUID")
	}
	if in.StartDate, err = parseDate("start_date", req.StartDate); err != nil {
		return in, err
	}
	if req.EndDate != "" {
		if in.EndDate, err = parseDatePtr("end_date", &req.EndDate); err != nil {
			return in, err
		}
	}
	return in, nil
}

// getRecurringRule godoc
//
//	@Summary	Get recurring rule
//	@Tags		recurring-rules
//	@Produce	json
//	@Security	BearerAuth
//	@Param		id	path		string	true	"Rule ID"	format(uuid)
//	@Success	200	{object}	RecurringRuleEnvelope
//	@Failure	401	{object}	httpx.ErrorResponse	"UNAUTHENTICATED"
//	@Failure	404	{object}	httpx.ErrorResponse	"RECURRING_RULE_NOT_FOUND"
//	@Router		/recurring-rules/{id} [get]
func (h *Handler) getRecurringRule(w http.ResponseWriter, r *http.Request) {
	h.ruleAction(w, r, func(uid, id uuid.UUID) (*domain.RecurringRule, error) {
		return h.svc.GetRecurringRule(r.Context(), uid, id)
	})
}

// updateRecurringRule godoc
//
//	@Summary		Update recurring rule
//	@Description	Partial update. Changing the schedule recomputes next_run_date (never before the last run). end_date "" removes the end date.
//	@Tags			recurring-rules
//	@Accept			json
//	@Produce		json
//	@Security		BearerAuth
//	@Param			id			path		string						true	"Rule ID"	format(uuid)
//	@Param			If-Match	header		string						false	"Expected version"
//	@Param			body		body		UpdateRecurringRuleRequest	true	"Fields to change"
//	@Success		200			{object}	RecurringRuleEnvelope
//	@Failure		401			{object}	httpx.ErrorResponse	"UNAUTHENTICATED"
//	@Failure		404			{object}	httpx.ErrorResponse	"RECURRING_RULE_NOT_FOUND / ACCOUNT_NOT_FOUND / CATEGORY_NOT_FOUND"
//	@Failure		409			{object}	httpx.ErrorResponse	"VERSION_CONFLICT"
//	@Failure		422			{object}	httpx.ErrorResponse	"VALIDATION_FAILED / RULE_ENDED / INVALID_FREQUENCY"
//	@Router			/recurring-rules/{id} [patch]
func (h *Handler) updateRecurringRule(w http.ResponseWriter, r *http.Request) {
	h.ruleAction(w, r, func(uid, id uuid.UUID) (*domain.RecurringRule, error) {
		ver, err := ifMatch(r)
		if err != nil {
			return nil, err
		}
		req, err := decodeAndValidate[UpdateRecurringRuleRequest](h, w, r)
		if err != nil {
			return nil, err
		}
		in := app.UpdateRecurringInput{UserID: uid, ID: id, ExpectedVersion: ver, Type: req.Type, Amount: req.Amount,
			Note: req.Note, Frequency: req.Frequency, Interval: req.Interval, Count: req.Count}
		if in.AccountID, err = parseUUIDPtr("account_id", req.AccountID); err != nil {
			return nil, err
		}
		if in.CategoryID, err = parseUUIDPtr("category_id", req.CategoryID); err != nil {
			return nil, err
		}
		if in.StartDate, err = parseDatePtr("start_date", req.StartDate); err != nil {
			return nil, err
		}
		if req.EndDate != nil {
			var end *time.Time
			if *req.EndDate != "" {
				if end, err = parseDatePtr("end_date", req.EndDate); err != nil {
					return nil, err
				}
			}
			in.EndDate = &end
		}
		return h.svc.UpdateRecurringRule(r.Context(), in)
	})
}

// deleteRecurringRule godoc
//
//	@Summary		Delete recurring rule
//	@Description	Stops future occurrences. Transactions already generated are kept.
//	@Tags			recurring-rules
//	@Security		BearerAuth
//	@Param			id	path	string	true	"Rule ID"	format(uuid)
//	@Success		204
//	@Failure		401	{object}	httpx.ErrorResponse	"UNAUTHENTICATED"
//	@Failure		404	{object}	httpx.ErrorResponse	"RECURRING_RULE_NOT_FOUND"
//	@Router			/recurring-rules/{id} [delete]
func (h *Handler) deleteRecurringRule(w http.ResponseWriter, r *http.Request) {
	h.deleteAction(w, r, domain.ErrRecurringNotFound, h.svc.DeleteRecurringRule)
}

// pauseRecurringRule godoc
//
//	@Summary	Pause recurring rule
//	@Tags		recurring-rules
//	@Accept		json
//	@Produce	json
//	@Security	BearerAuth
//	@Param		id		path		string						true	"Rule ID"	format(uuid)
//	@Param		body	body		PauseRecurringRuleRequest	false	"Optional reason"
//	@Success	200		{object}	RecurringRuleEnvelope
//	@Failure	401		{object}	httpx.ErrorResponse	"UNAUTHENTICATED"
//	@Failure	404		{object}	httpx.ErrorResponse	"RECURRING_RULE_NOT_FOUND"
//	@Failure	422		{object}	httpx.ErrorResponse	"RULE_ENDED"
//	@Router		/recurring-rules/{id}/pause [post]
func (h *Handler) pauseRecurringRule(w http.ResponseWriter, r *http.Request) {
	h.ruleAction(w, r, func(uid, id uuid.UUID) (*domain.RecurringRule, error) {
		var req PauseRecurringRuleRequest
		if r.ContentLength != 0 {
			var err error
			if req, err = decodeAndValidate[PauseRecurringRuleRequest](h, w, r); err != nil {
				return nil, err
			}
		}
		return h.svc.PauseRecurringRule(r.Context(), uid, id, req.Reason)
	})
}

// resumeRecurringRule godoc
//
//	@Summary		Resume recurring rule
//	@Description	Continues from today; occurrences missed while paused are skipped.
//	@Tags			recurring-rules
//	@Produce		json
//	@Security		BearerAuth
//	@Param			id	path		string	true	"Rule ID"	format(uuid)
//	@Success		200	{object}	RecurringRuleEnvelope
//	@Failure		401	{object}	httpx.ErrorResponse	"UNAUTHENTICATED"
//	@Failure		404	{object}	httpx.ErrorResponse	"RECURRING_RULE_NOT_FOUND"
//	@Failure		422	{object}	httpx.ErrorResponse	"RULE_ENDED"
//	@Router			/recurring-rules/{id}/resume [post]
func (h *Handler) resumeRecurringRule(w http.ResponseWriter, r *http.Request) {
	h.ruleAction(w, r, func(uid, id uuid.UUID) (*domain.RecurringRule, error) {
		return h.svc.ResumeRecurringRule(r.Context(), uid, id)
	})
}

func (h *Handler) ruleAction(w http.ResponseWriter, r *http.Request, fn func(uid, id uuid.UUID) (*domain.RecurringRule, error)) {
	uid, ok := userID(w, r)
	if !ok {
		return
	}
	id, err := pathID(r, domain.ErrRecurringNotFound)
	if err == nil {
		var x *domain.RecurringRule
		if x, err = fn(uid, id); err == nil {
			setETag(w, x.Version())
			httpx.Data(w, http.StatusOK, toRecurringRuleResponse(x))
			return
		}
	}
	httpx.WriteError(w, r, mapError(err))
}
